version: '3.8'
services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - .:/app
    restart: unless-stopped
